"""empty message

Revision ID: 8d777b28f6f7
Revises: 238fed61dda8
Create Date: 2023-03-12 02:13:05.086281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d777b28f6f7'
down_revision = '238fed61dda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('num_rooms',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('num_bathrooms',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(length=80),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('num_bathrooms',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('num_rooms',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###
